name: Run ESP32 Script

on:
  schedule:
  - cron: '30 6 8 6 *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install packages
        run: |
          pip install pandas numpy scikit-learn matplotlib requests

      - name: Run script
        run: python esp32.py
